baseurl = "/"
title = "VondMe"
googleAnalytics = "UA-121716305-3"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
# disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = true

[languages]
  [languages.pt]
    contentDir = "content/pt-br"
    languageName = "Português"
    weight = 1
  [languages.en]
    contentDir = "content/en-us"
    languageName = "English"
    weight = 2